# Generated by Django 4.1.7 on 2023-03-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuName', models.CharField(max_length=50)),
                ('stuID', models.CharField(max_length=10)),
                ('stuSex', models.CharField(default='M', max_length=2)),
                ('stuBirth', models.DateField()),
            ],
        ),
    ]
